language: node_js
node_js:
  - stable
script:
  - npm run build
  - npm run test
deploy:
  - provider: pages
    target-branch: gh-pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_KEY
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
cache:
  directories:
    - node_modules
