language: node_js
node_js:
  - stable
script:
  - npm run build
  - npm run test:coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then mkdir -p docs/dist && cp -a dist/jedi-validate.js docs/dist/ && cp -a example docs/example; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run stryker && mkdir -p docs/stryker && cp -a reports/mutation/html docs/stryker; fi
deploy:
  - provider: pages
    target-branch: gh-pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_KEY
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
